# workflow name
name: Generate release-artifacts

# on events
on:
  push:
    branches:
      - 'master'

# workflow tasks
jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Generate build files
        uses: thatisuday/go-cross-build@v1
        with:
            platforms: 'linux/amd64'
            package: 'main.go'
            name: 'webcam-uploader'
            compress: 'true'
            dest: 'dist'
